"use client";
import { FormEvent, useState } from "react";
import { aiAPI, GeneratePostInput } from "@/lib/api";
import { useToast } from "@/lib/toast-context";
import { HiClipboardDocument, HiSparkles, HiArrowPath } from "react-icons/hi2";

const initial: GeneratePostInput = { topic: "", platform: "LinkedIn", tone: "Professional", length: "Medium" };
export default function GeneratePage() {
  const [form, setForm] = useState(initial); const [content, setContent] = useState(""); const [loading, setLoading] = useState(false); const { showToast } = useToast();
  const generate = async (event?: FormEvent) => { event?.preventDefault(); if (!form.topic.trim()) return showToast("Please add a topic first.", "warning"); setLoading(true); try { setContent((await aiAPI.generate(form)).content); } catch (error) { showToast(error instanceof Error ? error.message : "Generation failed. Please try again.", "error"); } finally { setLoading(false); } };
  const set = <K extends keyof GeneratePostInput>(key: K, value: GeneratePostInput[K]) => setForm((p) => ({ ...p, [key]: value }));
  return <main className="min-h-[calc(100vh-5rem)] bg-[#08111c] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8494ff]">AI post generator</p><h1 className="mt-3 text-4xl font-black uppercase italic sm:text-5xl">Turn an idea into a post.</h1></div><div className="grid gap-6 lg:grid-cols-2"><form onSubmit={generate} className="rounded-3xl border border-white/10 bg-white/[.03] p-6 sm:p-8"><label className="block font-serif text-lg font-bold">Topic<textarea value={form.topic} onChange={(e) => set("topic", e.target.value)} placeholder="What do you want to talk about?" className="mt-3 min-h-36 w-full rounded-2xl border border-white/10 bg-[#0b1423] p-4 text-base font-sans text-white outline-none placeholder:text-slate-600 focus:border-[#7184ff]" /></label><div className="mt-5 grid gap-4 sm:grid-cols-3">{([['platform','Platform',['LinkedIn','Facebook','Instagram','X (Twitter)']],['tone','Tone',['Professional','Casual','Friendly','Persuasive','Funny']],['length','Length',['Short','Medium','Long']]] as const).map(([key,label,items]) => <label key={key} className="font-serif text-sm font-bold">{label}<select value={form[key]} onChange={(e) => set(key, e.target.value as never)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b1423] p-3 font-sans text-white outline-none">{items.map((x) => <option key={x}>{x}</option>)}</select></label>)}</div><button disabled={loading} className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#5067f5] px-5 py-4 font-bold disabled:opacity-60"><HiSparkles className={loading ? "animate-spin" : ""} />{loading ? "Generating..." : "Generate post"}</button></form><section className="rounded-3xl border border-white/10 bg-white/[.03] p-6 sm:p-8">{content ? <><p className="text-sm font-bold uppercase tracking-[.16em] text-[#8494ff]">Your draft</p><p className="mt-5 whitespace-pre-wrap font-serif text-lg leading-relaxed text-slate-200">{content}</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={async () => { await navigator.clipboard.writeText(content); showToast("Post copied to clipboard.", "success"); }} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 font-bold"><HiClipboardDocument />Copy</button><button onClick={() => generate()} disabled={loading} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 font-bold"><HiArrowPath />Regenerate</button></div></> : <div className="grid min-h-72 place-items-center text-center"><div><HiSparkles className="mx-auto text-5xl text-[#7184ff]" /><p className="mt-5 font-serif text-xl text-slate-400">Your generated post will appear here.</p></div></div>}</section></div></div></main>;
}
