"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { postsAPI, SavedPost } from "@/lib/api";
import { useToast } from "@/lib/toast-context";
import { useAuth } from "@/lib/auth-context";

export default function PostDetailsPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { user } = useAuth(); const { showToast } = useToast();
  const [post, setPost] = useState<SavedPost | null>(null); const [loading, setLoading] = useState(true); const [notFound, setNotFound] = useState(false); const [showDeleteModal, setShowDeleteModal] = useState(false);
  useEffect(() => { postsAPI.getById(id).then(setPost).catch(() => setNotFound(true)).finally(() => setLoading(false)); }, [id]);
  const deletePost = async () => { if (!post) return; try { await postsAPI.delete(post._id); showToast("Post deleted successfully.", "success"); router.push("/my-posts"); } catch (e) { showToast(e instanceof Error ? e.message : "Unable to delete post.", "error"); } };
  const handleDeleteClick = () => setShowDeleteModal(true);
  const handleDeleteConfirm = async () => { setShowDeleteModal(false); await deletePost(); };
  if (loading) return <main className="min-h-screen bg-[#08111c] px-5 py-16"><div className="mx-auto h-96 max-w-6xl animate-pulse rounded-3xl bg-white/5" /></main>;
  if (notFound || !post) return <main className="grid min-h-screen place-items-center bg-[#08111c] px-5 text-center text-white"><div><h1 className="text-4xl font-black">Post not found</h1><Link href="/features" className="mt-6 inline-block rounded-xl bg-[#5067f5] px-5 py-3 font-bold">Back to Explore</Link></div></main>;
  const ownsPost = user && (user.id === post.userId || user._id === post.userId);
  return <main className="min-h-screen bg-[#08111c] px-5 py-12 text-white sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/my-posts" className="text-[#9ba8ff]">← Back</Link><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_280px]"><article className="rounded-3xl border border-white/10 bg-white/[.03] p-6 sm:p-10"><div className="h-52 rounded-2xl bg-[radial-gradient(circle_at_30%_20%,#7184ff,transparent_35%),linear-gradient(135deg,#111b35,#0b1423)]" /><div className="mt-8 flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-[#5067f5]/20 px-3 py-1 text-[#b5bdff]">{post.platform}</span><span className="rounded-full bg-white/10 px-3 py-1">{post.tone}</span><span className="rounded-full bg-white/10 px-3 py-1">{post.length}</span></div><h1 className="mt-5 text-4xl font-black italic">{post.title}</h1><section className="mt-10"><h2 className="text-xl font-bold">Overview</h2><p className="mt-3 font-serif text-lg text-slate-400">{post.shortDescription}</p></section><section className="mt-10"><h2 className="text-xl font-bold">Generated Content</h2><p className="mt-3 whitespace-pre-wrap font-serif text-lg leading-relaxed text-slate-200">{post.generatedContent}</p></section><div className="mt-10 flex gap-3"><button onClick={() => navigator.clipboard.writeText(post.generatedContent).then(() => showToast("Post copied.", "success"))} className="rounded-xl bg-[#5067f5] px-5 py-3 font-bold">Copy Post</button>{ownsPost && <button onClick={handleDeleteClick} className="rounded-xl border border-red-400/30 px-5 py-3 font-bold text-red-300">Delete</button>}</div></article><aside className="h-fit rounded-3xl border border-white/10 bg-white/[.03] p-6 text-slate-300"><h2 className="font-bold text-white">Post details</h2><dl className="mt-5 space-y-4"><div><dt className="text-sm text-slate-500">Platform</dt><dd>{post.platform}</dd></div><div><dt className="text-sm text-slate-500">Tone</dt><dd>{post.tone}</dd></div><div><dt className="text-sm text-slate-500">Length</dt><dd>{post.length}</dd></div><div><dt className="text-sm text-slate-500">Created</dt><dd>{new Date(post.createdAt).toLocaleDateString()}</dd></div></dl></aside></div></div>{showDeleteModal && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/70 px-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0f172a] p-6 shadow-2xl"><h3 className="text-xl font-bold text-white">Delete this post?</h3><p className="mt-3 text-sm leading-6 text-slate-400">This action cannot be undone. The post will be removed from your saved posts list.</p><div className="mt-6 flex justify-end gap-3"><button onClick={() => setShowDeleteModal(false)} className="rounded-xl border border-white/10 px-4 py-2 font-semibold text-slate-200">Cancel</button><button onClick={handleDeleteConfirm} className="rounded-xl bg-red-500 px-4 py-2 font-semibold text-white">Delete</button></div></div></div>}</main>;
}
